// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/article/aiModifyOutline": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articleHandler"
                ],
                "summary": "使用 AI 修改大纲",
                "parameters": [
                    {
                        "description": "AI 修改大纲请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.AiModifyOutlineRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.OutlineSection"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/article/confirmOutline": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articleHandler"
                ],
                "summary": "确认大纲",
                "parameters": [
                    {
                        "description": "确认大纲请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.ConfirmOutlineRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/article/confirmTitle": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articleHandler"
                ],
                "summary": "确认标题并输入补充描述",
                "parameters": [
                    {
                        "description": "确认标题并输入补充描述请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.ConfirmTitleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/article/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articleHandler"
                ],
                "summary": "创建文章",
                "parameters": [
                    {
                        "description": "创建文章请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.CreateArticleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "integer",
                                            "format": "int64"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/article/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articleHandler"
                ],
                "summary": "删除文章",
                "parameters": [
                    {
                        "description": "删除文章请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/article/list": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articleHandler"
                ],
                "summary": "分页查询文章列表",
                "parameters": [
                    {
                        "description": "查询文章列表请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.QueryArticleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.ArticlePage"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/article/progress/{taskId}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articleHandler"
                ],
                "summary": "获取文章进度",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文章 ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文章进度",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/article/{taskId}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articleHandler"
                ],
                "summary": "获取文章",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文章 ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.ArticleInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "检查服务是否可用",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/add": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "userHandler"
                ],
                "summary": "创建用户（管理员）",
                "parameters": [
                    {
                        "description": "创建用户信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.AddUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "integer",
                                            "format": "int64"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "userHandler"
                ],
                "summary": "删除用户（管理员）",
                "parameters": [
                    {
                        "description": "删除用户信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/get": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "userHandler"
                ],
                "summary": "根据 ID 获取用户（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/get/vo": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "userHandler"
                ],
                "summary": "根据 ID 获取用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.UserInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/list/page/vo": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "userHandler"
                ],
                "summary": "分页查询用户列表（管理员）",
                "parameters": [
                    {
                        "description": "查询用户信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.QueryUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.PageResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/login": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "userHandler"
                ],
                "summary": "用户登录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.LoginUser"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "userHandler"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.LoginUser"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "userHandler"
                ],
                "summary": "用户注销",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "userHandler"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "integer",
                                            "format": "int64"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "userHandler"
                ],
                "summary": "更新用户（管理员）",
                "parameters": [
                    {
                        "description": "更新用户信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_romeokeita231_Article_Generator_internal_common.BaseResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.AddUserRequest": {
            "type": "object",
            "required": [
                "userAccount"
            ],
            "properties": {
                "userAccount": {
                    "type": "string"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.AiModifyOutlineRequest": {
            "type": "object",
            "required": [
                "modifySuggestion",
                "taskId"
            ],
            "properties": {
                "modifySuggestion": {
                    "type": "string"
                },
                "taskId": {
                    "type": "string"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.ArticleInfo": {
            "type": "object",
            "properties": {
                "completedTime": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "enabledImageMethods": {
                    "description": "允许的配图方式列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "errorMessage": {
                    "type": "string"
                },
                "fullContent": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.ImageResult"
                    }
                },
                "mainTitle": {
                    "type": "string"
                },
                "outline": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.OutlineSection"
                    }
                },
                "phase": {
                    "description": "当前阶段",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "style": {
                    "description": "文章风格",
                    "type": "string"
                },
                "subTitle": {
                    "type": "string"
                },
                "taskId": {
                    "type": "string"
                },
                "titleOptions": {
                    "description": "标题方案列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.TitleOption"
                    }
                },
                "topic": {
                    "type": "string"
                },
                "userDescription": {
                    "description": "用户补充描述",
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.ArticlePage": {
            "type": "object",
            "properties": {
                "pageNumber": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.ArticleInfo"
                    }
                },
                "totalPage": {
                    "type": "integer"
                },
                "totalRow": {
                    "type": "integer"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.ConfirmOutlineRequest": {
            "type": "object",
            "required": [
                "outline",
                "taskId"
            ],
            "properties": {
                "outline": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_romeokeita231_Article_Generator_internal_model.OutlineSection"
                    }
                },
                "taskId": {
                    "type": "string"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.ConfirmTitleRequest": {
            "type": "object",
            "required": [
                "selectedMainTitle",
                "selectedSubTitle",
                "taskId"
            ],
            "properties": {
                "selectedMainTitle": {
                    "type": "string"
                },
                "selectedSubTitle": {
                    "type": "string"
                },
                "taskId": {
                    "type": "string"
                },
                "userDescription": {
                    "description": "用户补充描述（可选）",
                    "type": "string"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.CreateArticleRequest": {
            "type": "object",
            "required": [
                "topic"
            ],
            "properties": {
                "enabledImageMethods": {
                    "description": "允许的配图方式，为空表示支持所有",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "style": {
                    "description": "文章风格，允许为空",
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.DeleteRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.ImageResult": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "keywords": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "placeholderID": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                },
                "sectionTitle": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.LoginRequest": {
            "type": "object",
            "required": [
                "userAccount",
                "userPassword"
            ],
            "properties": {
                "userAccount": {
                    "type": "string",
                    "minLength": 4
                },
                "userPassword": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.LoginUser": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "editTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "quota": {
                    "type": "integer"
                },
                "updateTime": {
                    "type": "string"
                },
                "userAccount": {
                    "type": "string"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                },
                "vipTime": {
                    "type": "string"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.OutlineSection": {
            "type": "object",
            "properties": {
                "points": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "section": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.PageResult": {
            "type": "object",
            "properties": {
                "pageNum": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "records": {},
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.QueryArticleRequest": {
            "type": "object",
            "properties": {
                "pageNum": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.QueryUserRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "pageNum": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "sortField": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "string"
                },
                "userAccount": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.RegisterRequest": {
            "type": "object",
            "required": [
                "checkPassword",
                "userAccount",
                "userPassword"
            ],
            "properties": {
                "checkPassword": {
                    "type": "string",
                    "minLength": 8
                },
                "userAccount": {
                    "type": "string",
                    "minLength": 4
                },
                "userPassword": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.TitleOption": {
            "type": "object",
            "properties": {
                "mainTitle": {
                    "type": "string"
                },
                "subTitle": {
                    "type": "string"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.UpdateUserRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.User": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "editTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "quota": {
                    "type": "integer"
                },
                "updateTime": {
                    "type": "string"
                },
                "userAccount": {
                    "type": "string"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                }
            }
        },
        "github_com_romeokeita231_Article_Generator_internal_model.UserInfo": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "editTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updateTime": {
                    "type": "string"
                },
                "userAccount": {
                    "type": "string"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                },
                "vipTime": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "AI Article Generator API",
	Description:      "Go backend API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
